export default Invoices = [
  {
    invoiceID: "#011801",
    shopName: "Anonymous Shop",
    date: "01/03/2021",
    InvItems: [
      {
        itemID: "#001",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#002",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#003",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#004",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#005",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
    ],
  },
  {
    invoiceID: "#011802",
    shopName: "Anonymous Shop",
    date: "01/03/2021",
    InvItems: [
      {
        itemID: "#001",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#002",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#003",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#004",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#005",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
    ],
  },
  {
    invoiceID: "#011803",
    shopName: "Anonymous Shop",
    date: "01/03/2021",
    InvItems: [
      {
        itemID: "#001",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#002",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#003",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#004",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#005",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
    ],
  },
  {
    invoiceID: "#011804",
    shopName: "Anonymous Shop",
    date: "01/03/2021",
    InvItems: [
      {
        itemID: "#001",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#002",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#003",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#004",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#005",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
    ],
  },
  {
    invoiceID: "#011805",
    shopName: "Anonymous Shop",
    date: "01/03/2021",
    InvItems: [
      {
        itemID: "#001",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#002",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#003",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#004",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
      {
        itemID: "#005",
        itemName: "Anonymous Item",
        unitPrice: "250",
        noOfItems: "10",
        totalPrice: "2500",
      },
    ],
  },
];
