export default StockItems = [
  {
    itemID: "#001",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "20",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#002",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "15",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#003",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "10",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#004",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "15",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#005",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "25",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#006",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "20",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#007",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "15",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#008",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "0",
    availability: false,
    store: "Colombo",
  },
  {
    itemID: "#009",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "15",
    availability: true,
    store: "Colombo",
  },
  {
    itemID: "#010",
    itemName: "Anonymous Item",
    unitPrice: "250",
    stock: "25",
    availability: true,
    store: "Colombo",
  },
];
